Default: &defaults
  user: yesodlab
  password: yesodlab
  host: localhost
  port: 3306
  database: YESODLAB
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: YESODLAB_TEST
  <<: *defaults

Staging:
  database: YESODLAB_STAGING
  poolsize: 100
  <<: *defaults

Production:
  database: YESODLAB_PRODUCTION
  poolsize: 100
  <<: *defaults
