Default: &defaults
  database: yesod-lab.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: yesod-lab_test.sqlite3
  <<: *defaults

Staging:
  database: yesod-lab_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: yesod-lab_production.sqlite3
  poolsize: 100
  <<: *defaults
